### ISSUE TITLE
🐛Bug: smooth scroll on Dialog close

### ISSUE THREAD

**Issue by jperchoc** [radix-svelte/radix-svelte#166]
**Describe the bug**
Since version 0.7.1, when smooth scrolling is enabled, a scroll from top page to current location is visible when closing a Dialog.

**To Reproduce**

- use version 0.7.1 of radix-svelte
- add `html { scroll-behavior: smooth; }` to  `app.css` file
- have a page with enough content to have a vertical scrollbar
- add a dialog
- when closing the dialog, the page scrolls from the top, which is very visible with smooth scrolling

This is visible on this [stackblitz](https://stackblitz.com/edit/node-as3egu?file=src%2Froutes%2F%2Bpage.svelte)

**Expected behavior**
Scrolling should be instant

**Screenshots**
[Demo here](https://stackblitz.com/edit/node-as3egu?file=src%2Froutes%2F%2Bpage.svelte)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chromium
 - Version: 113.0.5672.126

**Additional context**
The issue does not exist in older versions of radix-svelte. It seems this issue appeared with this PR: https://github.com/radix-svelte/radix-svelte/pull/159

**Comment by TGlide** [comment]
Should be fixed by https://github.com/radix-svelte/radix-svelte/releases/tag/v0.8.0
