### ISSUE TITLE
🐛Bug: Tooltip does not trigger on mobile

### ISSUE THREAD

**Issue by kylewardnz** [radix-svelte/radix-svelte#171]
**Describe the bug**
Tooltips are not openable on mobile via a click/tap

**To Reproduce**
1. go to the tooltip docs page: https://www.radix-svelte.com/docs/tooltip
2. open chrome dev tools
3. switch to mobile simulation
4. click the tooltip trigger
5. see that nothing opens

**Expected behavior**
Tooltips should be usable on mobile via a click/tap

**Screenshots**

https://github.com/radix-svelte/radix-svelte/assets/450516/935d8bec-1758-4aeb-92db-1299c9475e8e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 114.0.5735.134

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro Max
 - OS: 16.5.1
 - Browser: Safari
 - Version: N/A

**Additional context**

I'm unable to make a stackblitz for some reason, getting `TypeError: Cannot read properties of undefined (reading 'Root')` when trying to use the components. It's reproducible in the docs however: https://www.radix-svelte.com/docs/tooltip

**Comment by TGlide** [comment]
Hi! Tooltip is not supposed to open on tap: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role
