### ISSUE TITLE
✨ Component: Dropdown Menu

### ISSUE THREAD

**Issue by TGlide** [radix-svelte/radix-svelte#18]
- [ ] Implementation
- [ ] Example
- [ ] Animation
- [ ] Storybook/Histoire
- [ ] Tests
- [ ] Docs

**Comment by hcrawfdev** [comment]
I couldn't find a reference to this component in the documentation/code. Could this potentially be re-opened?

**Comment by TGlide** [comment]
@hcrawfdev Using the issues to track component progress has been deprecated in favor of the README roadmap :)
